### ISSUE TITLE
java.io.FileNotFoundException: results/coverages.json (No such file or directory)

### ISSUE THREAD

**Issue by laurentnoe** [yoann-dufresne/Smiles2Monomers#1]
Hi,

following the https://github.com/yoann-dufresne/Smiles2Monomers/#readme file to install,

and after some struggle 😃 with the `classpath` variable :

```
export CLASSPATH=${CLASSPATH}:${PWD}/build/lib/cdk-1.4.19.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/lib/libtw.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/lib/hamcrest-core.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/lib/json-simple-1.1.1.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/lib/junit.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/lib/xerces.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/build/lib/json.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/build/lib/libtw.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/build/lib/hamcrest-core.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/build/lib/junit.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/build/lib/cdk.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/build/lib/xerces.jar
export CLASSPATH=${CLASSPATH}:${PWD}/build/s2m.jar
echo $CLASSPATH
```

and  after some struggle 😃 with missing  data (json files)
* data/monomers.json: The monomers to search for
* data/rules.json: The binding rules
* data/learning.json: Learning base of polymers

(where could i find them online ? so i took the ones available here https://bioinfo.lifl.fr/NRP/smiles2monomers/data/  without the 'serial' directory, otherwise there is a fail ...)

and the example taken directly from https://github.com/yoann-dufresne/Smiles2Monomers/wiki/Json-formats for the `polymers.json`, or by copying 'data/peptides.json' to 'data/polymers.json',

i finally came to this `java.io.FileNotFoundException` 😃 when running `ant s2m`

```
ant s2m
Buildfile: Smiles2Monomers/build.xml

s2m:
     [java] --- Loading ---
     [java] The smiles for actinomycin pip1-alpha contains character '.'
     [java] The '.' means that the smiles is composed of more than one molecule.
     [java] Please split the smiles in two distinct smiles.
     [java] The smiles for emerimicin IIB contains character '.'
     [java] The '.' means that the smiles is composed of more than one molecule.
     [java] Please split the smiles in two distinct smiles.
     [java] The smiles for emerimicin III contains character '.'
     [java] The '.' means that the smiles is composed of more than one molecule.
     [java] Please split the smiles in two distinct smiles.
     [java] Loading time : 26s
     [java] --- Monomers search ---
     [java] +Strict matching
     [java] ++Search residues
...
...
     [java] +Strict matching
     [java] ++Search residues
     [java] Search time : 7s
     [java] --- Output creations ---
     [java] java.io.FileNotFoundException: results/coverages.json (No such file or directory)
     [java] 	at java.base/java.io.FileOutputStream.open0(Native Method)
     [java] 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
     [java] 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
     [java] 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
     [java] 	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
     [java] 	at io.loaders.json.AbstractJsonLoader.saveFile(Unknown Source)
     [java] 	at main.ProcessPolymers.main(Unknown Source)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:218)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:155)
     [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:891)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:231)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
     [java] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     [java] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
     [java] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:449)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
     [java] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
     [java] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
     [java] 	at org.apache.tools.ant.Main.runBuild(Main.java:827)
     [java] 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
     [java] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
     [java] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
     [java] Ouputing time : 8s
     [java] --- Ended ---

BUILD SUCCESSFUL
Total time: 42 seconds
```

i suspect this coverage must be generate but there is no command line for this ?

PS : https://bioinfo.lifl.fr/NRP/smiles2monomers/Smiles2Monomers.zip link is dead ?

**Comment by laurentnoe** [comment]
`ln -s data results`   is that ?

since the _picture_ human readable result is in
`build/results/s2m.html`
after the run, is `ln -s build/results results`more appropriate ?

PS : i tried to get the command line from s2m, no idea how to manage this ?

**Comment by yoann-dufresne** [comment]
Wow, I do not remind anything of this code, it was a long time ago.
Does the ln trick working ?

I looked inside of the main and it seems that I was stupid and did not use any command line parser.
The only way to know options is to look inside of :
https://github.com/yoann-dufresne/Smiles2Monomers/blob/master/src/main/ProcessPolymers.java

But I think that this software should not be used anymore.
I am not maintaining it and I completely changed my research since a few years, so I will not change this code.

Why do you need this code for ? Maybe we can quickly find an alternative.

For the dead link I don't know.
You have to contact Areski for that.

**Comment by laurentnoe** [comment]
Sorry for the delay, and thank you for the link to 
[https://github.com/yoann-dufresne/Smiles2Monomers/blob/master/src/main/ProcessPolymers.java](https://github.com/yoann-dufresne/Smiles2Monomers/blob/master/src/main/ProcessPolymers.java)
👍👍 

abou the missing file  : yes, one of the  `ln -s data results` or `ln -s build/results results` worked perfectly  
(i dont remember which one now 🤣 :  one of the directory was missing, so the file inside was too) 
👍 

i will ask Areski about this file, but the dead link is a true missing file (after a full webserver search 😁)  : may be some corresponding backup somewhere ?

**Comment by yoann-dufresne** [comment]
No I do not have any backup except here on github. Maybe the Univ Lille local git (I do not have access 5 yrs after) ?
