### ISSUE TITLE
preCompute fails

### ISSUE THREAD

**Issue by YasinEl** [yoann-dufresne/Smiles2Monomers#2]
Hello I am trying to use your package on Windows10, but unfortunately the ant preCompute command fails with 
```

C:\Users\elabi\Smiles2Monomers>ant preCompute
Buildfile: C:\Users\elabi\Smiles2Monomers\build.xml

preCompute:
     [java] JVM args ignored when same JVM is used.

BUILD FAILED
C:\Users\elabi\Smiles2Monomers\build.xml:81: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:425)
        at org.apache.tools.ant.types.Permissions.setSecurityManager(Permissions.java:103)
        at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:216)
        at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:155)
        at org.apache.tools.ant.taskdefs.Java.run(Java.java:891)
        at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:231)
        at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
        at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.Main.runBuild(Main.java:818)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

Total time: 0 seconds
```
Thank you a lot for your package and hope there is a solution to this!

**Comment by yoann-dufresne** [comment]
Hello @YasinEl ,
I'm sorry but this code is very old and is deprecated today.
I stopped this topic 7 years ago and I will not change anything in this repo.
For more up to date software, you should contact the [Norine team](https://bioinfo.lifl.fr/norine/).
